### PR TITLE
Add release to github step

### PR DESCRIPTION
**Pull request by MancunianSam**
- Add release to github step.
- Temporary changes to test the release to github step
- More temporary changes. I'll clean up after
- Construct the upload url properly
- Use filename to label the uploaded artifact
- Use the filename for the name and label
- Remove temporary code used for testing

### CODE REVIEW

**Review by TomJKing — COMMENTED** [review]
Looks good. Does this mean the lambda artifact is stored on github? Sorry, being a bit slow.

**Comment by MancunianSam** [comment]
It does yeah. It makes the performance checks stuff easier because I don't have to worry about cross account permissions. I don't think there's any problem with having the jars public as anything secret should use environment variables. What do you think? Can you see any reason not too?,

**Comment by TomJKing** [comment]
Sounds OK to me. So this would apply to all the lambdas we use?

**Comment by MancunianSam** [comment]
It will do. With the changes you've made to the file format, I'll have to update the Jenkinsfile in there separately but that's fine.

**Review by TomJKing — APPROVED** [review]

**Pull request merged**
